model_args:
  n_heads: 4
  k_interests: 16
  embed_dim: 16
  seq_len: 50
  intermediate_size: 64
  hidden_dropout_prob: 0.2
  attn_dropout_prob: 0.2
  hidden_act: "relu"
  layer_norm_eps: 1e-12
  padding_idx: -1
  reload_model: False
  save_path: "./data_platform/output/ml/checkpoints"

  item_num: 22700
  category_num: 30
  brand_num: 740
  price_bucket_num: 10
  time_bucket_num: 9
  event_type_num: 3



data_args:
  data_path: "./data_platform/output/ml/bst_split/train.jsonl"
  num_workers: 4
  shuffle: True
  max_history_len: 5

  train_data_path: "./data_platform/output/ml/bst_split/train.jsonl"
  val_data_path: "./data_platform/output/ml/bst_split/val.jsonl"
  test_data_path: "./data_platform/output/ml/bst_split/test.jsonl"

  padding_idx: -1


training_args:
  num_epochs: 10
  learning_rate: 0.001
  weight_decay: 0.00001
  batch_size: 16
  num_workers: 4
