[project]
name = "recsys-analytics"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "boto3==1.35.36",
  "dbt-trino==1.10.2",
  "psycopg2-binary==2.9.12",
  "pyspark==3.5.8",
  "pyyaml>=6,<7",
  "trino==0.338.0",
]

[dependency-groups]
dev = [
  "pytest>=9,<10",
  "pytest-cov>=7,<8",
]

[tool.setuptools.packages.find]
where = ["src"]
