[build-system]
requires = ["setuptools>=83"]
build-backend = "setuptools.build_meta"

[project]
name = "recsys-inference-api"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "httpx>=0.28.1,<1",
  "jaraco.context==6.1.0",
  "numpy>=2.2.6,<3",
  "recsys-serving-common",
  "setuptools==83.0.0",
  "tritonclient[grpc]>=2.54,<3",
  "uvicorn>=0.34,<1",
  "wheel==0.46.2",
]

[tool.uv.sources]
recsys-serving-common = { path = "../shared", editable = true }

[dependency-groups]
dev = [
  "hypothesis>=6.155.7,<7",
  "pytest>=9,<10",
  "pytest-cov>=7,<8",
  "pyyaml>=6,<7",
]

[tool.setuptools.packages.find]
where = ["src"]
